# Source language and JDK version to use
language: java
jdk: oraclejdk7

# Compile and package JAR and set build properties
install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}
script: echo "No... no... Mister Gradle no here."

# Perform steps after compilation/test success
after_success:
  # Get files for use with build, namely the custom Maven settings.xml
  - "git clone https://github.com/flow/travis-ci-resources.git target/travis"
  # Check if commit is not a pull request, if repo is official, and branch is master, generate and deploy artifacts and reports
  - "[[ $TRAVIS_PULL_REQUEST == false ]] && [[ $TRAVIS_REPO_SLUG == flow/flow-cerealization ]] && [[ $TRAVIS_BRANCH == master ]] && mvn javadoc:jar source:jar cobertura:cobertura coveralls:cobertura -DserviceJobId=$TRAVIS_JOB_ID deploy --settings target/travis/settings.xml"

# Notification services
notifications:
  # Disable build status email notifications, until the issue with forks is fixed
  email: false
  webhooks:
    # Send build information and status to Notifico
    - http://n.tkte.ch/h/2038/s1-vgwQBXo6CiTpkjY8K2Rz_

# Environmental system variables
env:
  global:
    # Make the log output cleaner
    - TERM=dumb
    # Super secure, encrypted variables! Ssssh!
    - secure: "MBgibkYC6YSfac0OxPOz+tea4U96Kt9Pt/cSnn5v6eEOpdKDxCIbHvsVtXVX2Aw++Y8fDwI0AO+OdUpzQWxGx8cQKcO0FQSUtLVL+Kr4ULdtjpE2n7sgA5alseOegnHOCCRtY4DQ/3wLTQ4zO3hWwCwK6S/LLox7Z8vMEDIrqxs="
    - secure: "guEuB11yhQj8nkVrTHmsXLETwDY4duGimLUBoFQ7LSgkdJfiJDPDToYUYrDofqCyR/STXuT+r1hwuJEwcAwVyzYUEazhNo0mbBLCZFp6xZ2O3CkSlTc9kIPdL30+wdnOyEJDAhsKQGBA8ebPikeuu/I34c1Fh1iGMoNcbFfG+yc="
